models/Weather.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "weather".
 *
 * @property int $id
 * @property string $date
 * @property array $morning
 * @property array $day
 * @property array $evening
 * @property array $night
 */
class Weather extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'weather';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['date', 'morning', 'day', 'evening', 'night'], 'required'],
            [['date', 'morning', 'day', 'evening', 'night'], 'safe'],
            [['date'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'date' => 'Date',
            'morning' => 'Morning',
            'day' => 'Day',
            'evening' => 'Evening',
            'night' => 'Night',
        ];
    }

    public function getM(): array {
        return json_decode($this->morning, true);
    }

    public function getD(): array {
        return json_decode($this->day, true);
    }

    public function getE(): array {
        return json_decode($this->evening, true);
    }

    public function getN(): array {
        return json_decode($this->night, true);
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use app\models\Weather;


class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex(): string
    {
        $weatherModel = Weather::findOne(['date' => date("Y-m-d")]);
        return $this->render('index', ['weatherModel' => $weatherModel]);
        
    }

    public function actionWeek(): string {
        $date = date("Y-m-d");
        $dateWeek = date("Y-m-d",strtotime($date."+6 DAY"));
        $weatherModels = Weather::find()
            ->where(['>=', 'date', $date])
            ->andWhere(['<=', 'date', $dateWeek])
            ->all();
        return $this->render('week', [
            'weatherModels' => $weatherModels,
            'date' => $date,
            'dateWeek' => $dateWeek,
        ]);
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\assets\AppAsset;
use yii\helpers\Url;
use yii\helpers\Html;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand"><span class="glyphicon glyphicon-cloud" aria-hidden="true"></span></span>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="<?=Url::to(['site/index'])?>">Сегодня</a></li>
        <li><a href="<?=Url::to(['site/week'])?>">На неделю</a></li>

      </ul>


    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<?= $content ?>


<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'Погода на день';
?>


<div class="container">
    <?php if($weatherModel): ?>
        <div class="page-header">
            <h1>Погода на сегодня <small><?=$weatherModel->date?></small></h1>
        </div>

        <div class="weath">
            <div class="daypart">Утром</div>
            <div class="temp"><?=$weatherModel->m['tMin']?>...<?=$weatherModel->m['tMax']?> <small><?=$weatherModel->m['condition']?></small></div>
        </div>

        <div class="weath">
            <div class="daypart">Днем</div>
            <div class="temp"><?=$weatherModel->d['tMin']?>...<?=$weatherModel->d['tMax']?> <small><?=$weatherModel->d['condition']?></small></div>
         </div>

        <div class="weath">
            <div class="daypart">Вечером</div>
            <div class="temp"><?=$weatherModel->e['tMin']?>...<?=$weatherModel->e['tMax']?> <small><?=$weatherModel->e['condition']?></small></div>
 
        </div>

        <div class="weath">
            <div class="daypart">Ночью</div>
            <div class="temp"><?=$weatherModel->n['tMin']?>...<?=$weatherModel->n['tMax']?> <small><?=$weatherModel->n['condition']?></small></div>
        </div>

    <?php else: ?>
        <div class="alert alert-warning" role="alert">Нет данных о погоде</div>
    <?php endif; ?>
</div>

views/site/week.php
<?php

/* @var $this yii\web\View */

$this->title = 'Погода на неделю';
?>


<div class="container">
    <?php if($weatherModels): ?>
        <div class="page-header">
            <h1>Погода на неделю <small><?=$date?> - <?=$dateWeek?></small></h1>
        </div>

        <?php foreach ($weatherModels as $weatherModel): ?>

            <div>
                <h2><?=$weatherModel->date?></h2>
            </div>

            <div class="weath">
                <div class="daypart">Утром</div>
                <div class="temp"><?=$weatherModel->m['tMin']?>...<?=$weatherModel->m['tMax']?> <small><?=$weatherModel->m['condition']?></small></div>
            </div>

            <div class="weath">
                <div class="daypart">Днем</div>
                <div class="temp"><?=$weatherModel->d['tMin']?>...<?=$weatherModel->d['tMax']?> <small><?=$weatherModel->d['condition']?></small></div>
            </div>

            <div class="weath">
                <div class="daypart">Вечером</div>
                <div class="temp"><?=$weatherModel->e['tMin']?>...<?=$weatherModel->e['tMax']?> <small><?=$weatherModel->e['condition']?></small></div>
    
            </div>

            <div class="weath">
                <div class="daypart">Ночью</div>
                <div class="temp"><?=$weatherModel->n['tMin']?>...<?=$weatherModel->n['tMax']?> <small><?=$weatherModel->n['condition']?></small></div>
            </div>

        <?php endforeach; ?>

    <?php else: ?>
        <div class="alert alert-warning" role="alert">Нет данных о погоде</div>
    <?php endif; ?>
</div>